# Generated by Django 6.0 on 2025-12-18 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_alter_redactor_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='publishers',
            field=models.ManyToManyField(related_name='newspapers', to=settings.AUTH_USER_MODEL),
        ),
    ]
